team-michael/notifly-docs

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/advanced/ios-push-extension.mdx
조금 전 PR에서 줄바꿈이 먹지 않는 버그 수정합니다.
> fix: trivial bug fix on documnetation of ios push extension

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/advanced/ios-push-extension.mdx
fix: flutter push extension(ios) required version fix
> fix: flutter push extension(ios) required version fix

- docusaurus.config.js
- i18n/ko/docusaurus-theme-classic/footer.json
> chore: update copyright

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.md
- i18n/ko/docusaurus-plugin-content-docs/current/user-guide/amplitude/amplitude-introduction.md
> chore: update contact email address

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.md
* 다중 사용자 속성 업데이트 API 사용법 문서에 업데이트
> feat: add multiple users update api usage

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/javascript-sdk.mdx
> feat: add JS SDK version badges

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/javascript-sdk.mdx
> feat: improve push permission request

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/google-tag-manager.mdx
- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/javascript-sdk.mdx
> feat: revise js-sdk docs

- docusaurus.config.js
- static/js/redirect-based-on-locale.js
Locale이 ko인 경우, `/ko`로 redirect 시킵니다.
> feat: redirect page when locale is ko

- docs/user-guide/faq/index.md
- i18n/ko/docusaurus-plugin-content-docs/current/user-guide/faq/index.md
> feat: setup FAQ page

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.md
* 문자, 알림톡, 친구톡 발송 HTTP API 가이드 문서 추가
> feat: add http message send api guide

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.md
Merge 과정에서 삭제된 set user properties 문서를 다시 추가합니다.
> feat: recover a remove http api guide

- static/naver7ed34addafe11cbfacc8aa6c6ff0376b.html
> feat: naver site verification

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.md
> feat: update http api authentication method

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/javascript-sdk.mdx
sdk script를 동기식으로 로딩하도록 가이드 업데이트
> feat: update javascript sdk including guide

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/advanced/flutter-sdk-advanced.mdx
- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/flutter-sdk.mdx
> feat: update flutter docs

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/advanced/flutter-sdk-advanced.mdx
- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/advanced/react-native-sdk-advanced.mdx
- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/javascript-sdk.mdx
- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/react-native-sdk.mdx
React Native Documentation 업데이트 합니다.
> feat: update react native documentation

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.mdx
> feat: add delete users api docs

- i18n/ko/docusaurus-plugin-content-docs/current/user-guide/kakaotalk/friendtalk-guide.md
> chore: fix incorrect description about friendtalk;

- docs/developer-guide/http-api/http-api-guide.mdx
- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/advanced/react-native-sdk-advanced.mdx
- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/flutter-sdk.mdx
- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/javascript-sdk.mdx
- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.mdx
> Http api english

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/advanced/ios-push-extension.mdx
> fix: fix push extension docs

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.mdx
HTTP API documentation update 합니다.
> feat: update http api documentation

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/react-native-sdk.mdx
> feat: update RN docs

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.mdx
track-event http api 문서 업데이트. (batch logging)
> feat: update track-event docs

- docs/developer-guide/client-sdk/advanced/ios-push-extension.mdx
- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/advanced/ios-push-extension.mdx
> chore: change ios sdk lastest version

- docs/user-guide/in-app-message/_category_.json
- docs/user-guide/in-app-message/guide.md
- docs/user-guide/web-message/_category_.json
- docs/user-guide/web-message/guide.mdx
- i18n/ko/docusaurus-plugin-content-docs/current.json
- i18n/ko/docusaurus-plugin-content-docs/current/user-guide/in-app-message/_category_.json
- i18n/ko/docusaurus-plugin-content-docs/current/user-guide/web-message/_category_.json
In App Message -> In App Popup
> chore: in app message to in app popup

- docs/developer-guide/client-sdk/advanced/ios-push-extension.mdx
- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/advanced/ios-push-extension.mdx
> chore: sepatate push extension cocoapod

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.mdx
- i18n/ko/docusaurus-plugin-content-docs/current/user-guide/campaigns/basic.md
> chore: update api campaign description

- docs/user-guide/campaigns/personalization/_category_.json
- docs/user-guide/campaigns/personalization/advanced.md
- docs/user-guide/campaigns/personalization/basic.md
- i18n/ko/docusaurus-plugin-content-docs/current.json
- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.mdx
- i18n/ko/docusaurus-plugin-content-docs/current/user-guide/campaigns/personalization/_category_.json
- i18n/ko/docusaurus-plugin-content-docs/current/user-guide/campaigns/personalization/advanced.md
- i18n/ko/docusaurus-plugin-content-docs/current/user-guide/campaigns/personalization/basic.md
* 알림톡 대체 발송 파라메터 가이드 추가
* connected_content 문서 추가
> feat: add alimtalk resend guide

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.mdx
Text Message API 설명에 lms type 내용 추가.
> feat: add lms type to text message api guide

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.mdx
> fix: fix typo

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/flutter-sdk.mdx
- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/react-native-sdk.mdx
> chore: ios push notification extension recommended

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/advanced/android-sdk-advanced.mdx
* android sdk 1.10.0 에 추가된 notification interceptor guide문서 추가
> feat: add notification interceptor guide

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.mdx
> feat: add block service guide

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.mdx
> feat: align headers

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.mdx
> feat: add link to Authorization endpoint

- docs/developer-guide/http-api/http-api-guide.mdx
- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.mdx
https://github.com/team-michael/notifly-event/pull/1465
NOTIFLY-2159
> feat: add email type to campaign api

- i18n/ko/docusaurus-plugin-content-docs/current/user-guide/cafe24/cafe24-spec.mdx
> feat: add order_canceled event

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.mdx
> feat: add resendSendNo

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.mdx
> feat: add documentation for Campaign Statistics Retrieval Endpoint

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.mdx
text message api에 sendNo 항목을 추가합니다.
> feat: add send text message api sendNo

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.mdx
* 카카오 알림톡 관리 API 문서 추가
* HTTP API 문서 재정렬
> feat: add kakao alimtalk management api doc

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/android-sdk.mdx
> fix: update latest android version example

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.mdx
> docs: fix the level for the api keys per product

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/android-sdk.mdx
- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/flutter-sdk.mdx
- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/ios-sdk.mdx
- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/react-native-sdk.mdx
- `getNotiflyUserId` 메소드를 문서에 추가합니다.
- 민규님: 메소드 설명 괜찮은지 확인 부탁드립니다
- 수민님: ios, rn 인터페이스 확인 부탁드립니다
https://notifly-greybox.slack.com/archives/C06BNQAU2MV/p1737354269661879
> docs: add `getNotiflyUserId` method

- src/css/custom.css
> refactor: apply minor style changes for better readability

- .github/workflows/deploy.yml
> fix: deploy action

- .github/workflows/deploy.yml
https://github.com/actions/upload-pages-artifact
> chore: update plugin action version

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/advanced/android-sdk-advanced.mdx
- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/advanced/ios-sdk-advanced.mdx
> feat: add addInAppMessageEventListener usage docs

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.mdx
* API 기반 발송 호출 endpoint restful하게 수정.
> feat: update campaign trigger api endpoint

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/advanced/android-sdk-advanced.mdx
- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/client-sdk/advanced/ios-sdk-advanced.mdx
* android sdk event params type 변경
> feat: update android sdk event params

- i18n/ko/docusaurus-plugin-content-docs/current.json
- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.mdx
> docs: user journey triggering

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.mdx
- export data 관련 문서에 일부 path가 잘못 들어가있어서 수정합니다.
> fix: fix typo _ -> -

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.mdx
- fix the difference between docs and the actual response
- add timeout to Data Export
> fix: fix statistics response

- i18n/ko/docusaurus-plugin-content-docs/current/developer-guide/http-api/http-api-guide.mdx
- Data Export에 새로운 필드를 추가합니다.
- isMessageDataIncluded
> feat: update isMessageDataIncluded
